app = "drone-report"
primary_region = "fra"

[build]
  image = "gotenberg/gotenberg:8"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
